projectceladon/minigbm

cros_gralloc/cros_gralloc_driver.cc

Add handle closing function to avoid resource leak.
Use clang-format-3.9 to correct some format errors.
Test: DUT boot successful
Tracked-On: OAM-81026
Sighed-off-by: Yuanzhe, Liu <yuanzhe.liu@intel.com>
Change-Id: Ib39eefd406eca5285375251d86f4bba0081f50d6

Fix klocwork issues in GFX domain

---

drv.c

Add a resource release function.
The fd handle is blended with drv struct, so we can only
close it in drv_destory function.

Fix klocwork issue in GFX domain

---

Android.mk

This is to help rename gralloc library name from
"TARGET_BOARD_PLATFORM" to "TARGET_GFX_INTEL".
Tracked-On: OAM-93101
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>

Rename gralloc target to "celadon"

---

i915.c

The DRM_FORMAT_ABGR2101010 format will be used by Android Media
framework for software codec of AV1Hdr, and the usage flag request
as:
BO_USE_SW_READ_RARELY
BO_USE_SW_READ_OFTEN
BO_USE_SW_WRITE_RARELY
BO_USE_SW_WRITE_OFTEN
Tracked-On: OAM-95578
Signed-off-by: Yang, Dong <dong.yang@intel.com>

add more usage flag for  DRM_FORMAT_ABGR2101010

---

cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Mapper.cc

Camera preview use YCbCr, and will be converted to resolved format
NV12. NV12 is one private defined format. So the descriptor.format
is not same with crosHandle->droid_format. Suppress the check here.
Tracked-On: OAM-95595
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>

INTERNAL: Fix unsupported format issue for camera preview

---

i915.c

For DRM_FORMAT_R8, we don't need align the stride. This
change could help fix allocator issues in CtsNNAPITestCases.
Tracked-On: OAM-95685
Signed-off-by: Ren Chenglei chenglei.ren@intel.com

INTERNAL: Fix CtsNNAPITestCases failures

---

i915.c

Add BO_USE_SW_MASK usage to DRM_FORMAT_RGB888 format,
this is required by Android R CTS.
Test: android.hardware.cts.HardwareBufferTest#testCreate
Tracked-On: OAM-95726
Signed-off-by: Ren Chenglei chenglei.ren@intel.com

INTERNAL: Fix CtsHardwareTestCases failures

---

cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc1/cros_gralloc1_module.h
cros_gralloc/i915_private_android_types.h

1. native_handle_* need native_handle_t instead of
buffer_handle_t, this conflicts with mapper 2.0
release function
2. importBuffer call native_handle_clone, which will
have "malloc", then we need use "free" by
native_handle_delete in case of memory leak, which
is called in private defined API freeBuffer
3. We should use Android official define API release
instead of private defined API freeBuffer; so we
need remove native_handle_clone in importBuffer
and use release directly
Tracked-On: OAM-96807
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>

INTERNAL: Refine importBuffer & freeBuffer

---

cros_gralloc/gralloc1/cros_gralloc1_module.cc

Inside the release function (CrosGralloc1::release())
native_handle_close() and native_handle_delete() functions are
getting called after driver release function call (driver->release()).
In driver release function these are already cleaned up.
Inside driver release function native_handle_close() is
called  inside destructor of cros_gralloc_buffer.
Tracked-On: OAM-97019
Signed-off-by: Kaushlendra Kumar <kaushalendra.kumar@intel.com>
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>

INTERNAL: fix of suspend/resume issue

---

cros_gralloc/cros_gralloc_driver.cc

getBackingStore() should return a globally unique value for a
dedicated graphics buffer, the graphics buffers will share between
different modules like display and codec, the unique value will be
used to identify specifi memory.
Tracked-On: OAM-97062
Signed-off-by: Yang, Dong <dong.yang@intel.com>

INTERNAL: getBackingStore() return unique value

---

cros_gralloc/gralloc1/cros_gralloc1_module.cc

invalid mutex result in variable of ref_count cannot be protected
property, trigger refree crash during media CTS.
Tracked-On: OAM-99957
Signed-off-by: Yang, Dong <dong.yang@intel.com>

INTERNAL: fix invalid mutex issue

---

cros_gralloc/cros_gralloc_driver.cc

The drv_kms_ == drv_render_ when not in kmsro mode.
Then only destroy driver once to avoid crash.
Tracked-On: OAM-100133
Signed-off-by: HeYue <yue.he@intel.com>

If is not kmsro mode, only destroy driver once

---

cros_gralloc/cros_gralloc_driver.cc
cros_gralloc/cros_gralloc_driver.h
cros_gralloc/gralloc0/gralloc0.cc
cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Allocator.cc
cros_gralloc/gralloc4/CrosGralloc4Mapper.cc

The video format have scanout flag but need use i915 driver
to allocate.
Tracked-On: OAM-101728
Signed-off-by: HeYue <yue.he@intel.com>

Enable the hw codec in SRIOV mode

---

cros_gralloc/cros_gralloc_driver.cc
drv.c
drv.h
drv_priv.h
gbm.c
i915.c

When in sriov mode, MMAP_GTT will fail for tiled buffer. Only alloc no tile buffer for sriov to avoid potential map fail on tiled buffer. Tried with gfxbench, performance affect is not obvious.
Tracked-On: OAM-105096
Signed-off-by: chenyanxzhu <chenyanx.zhu@intel.com>

Alloc no-tile buffer when sriov mode

---

i915.c

Change i915_get_gen to i915_get_genx10 to support versions with decimal value. Remove GEN3, which is no longer supported. Add more device id for GEN9 and GEN12.
Tracked-On:
Signed-off-by: chenyanxzhu <chenyanx.zhu@intel.com>

Refine gpu generation info

---

cros_gralloc/cros_gralloc_driver.cc
drv.c
drv.h
drv_priv.h
gbm.c
i915.c

Alloc no-tile buffer when sriov mode
If has dGPU, do not use Tiling Y.
Tracked-On: OAM-105855

Refine the init function and fix issue

---

i915.c

For sw usage, allocate linear buffer.
Tracked-On: OAM-106982
Signed-off-by: HeYue <yue.he@intel.com>

INTERNAL: Allocate tiling buffer for hw usage

---

cros_gralloc/cros_gralloc_helpers.cc
cros_gralloc/cros_gralloc_helpers.h
cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Mapper.cc

when we use format HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED to allocate the buffer, we get the buffer with format DRM_FORMAT_XBGR8888. The validateBufferSize will return an error because format mismatch. So we should ignore this type.
Tracked-On: OAM-110999

Fixed the validateBufferSize issue

---

i915.c

The hypervisor signatures of kernel 5.10 and
5.15 are different.
Tracked-On: OAM-111639

INTERNAL: Adjust the condition to check KVM

---

cros_gralloc/gralloc4/CrosGralloc4Mapper.cc

The function validateBufferSize fails when sw codec allocates buffer with HAL_PIXEL_FORMAT_YCBCR_P010. The reason is that the pixel format will be converted to drm format for allocating buffer, then the format of the handle is assigned to HAL_PIXEL_ format type with i915_private_invert_format, but the descriptor.format is still the pixel format, they must be different when checked in validateBufferSize. So we check the format type after uniformly converting the pixel/HAL format to drm format.
Tracked-On: OAM-112372

[SMR0] Fixed the issue that sw codec fails to validate 10-bit type buffer

---

cros_gralloc/cros_gralloc_helpers.cc
cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Allocator.cc
cros_gralloc/gralloc4/CrosGralloc4Utils.cc
cros_gralloc/i915_private_android.cc
drv.c
drv.h
i915.c
virtio_gpu.c

Instead of printing all logs with ERROR level, some logs just need INFO level.
Tracked-On: OAM-112267

Add print level INFO

---

cros_gralloc/cros_gralloc_driver.cc
cros_gralloc/cros_gralloc_driver.h
i915.c

As the prelim kernel has been reverted to previous PKT kernel,
so scanout buffer allocation should be reverted to be using
i915, instead of virtio-gpu, and with tiling format instead of linear.

Revert for using prev kernel

---

i915.c

In VM if run vulkan on iGPU, i915_dev->has_fence_reg is 0, so DRM_IOCTL_I915_GEM_SET_TILING and
DRM_IOCTL_I915_GEM_GET_TILING will never be invoked. Meanwhile if on dg2, i915_dev->has_fence_reg also is 0. So the flag 'i915_dev->has_fence_reg' can't be using to check if invoke GET_TILING,SET_TILING.
Consider if run vulkan app not on dg2, should invoke GET_TILING,SET_TILING.
Tracked-On: OAM-113503

Fix vulkan app can't display on iGPU in VM

---

i915.c
i915_private.c
i915_private.h

Resolve dgpu video color disorder issue

---

i915.c

TODO: it is WA to use local memory for NV12
to improve deconding score.
Tracked-On: OAM-113684

NV12 decoder use local memory

---

i915.c

Tith performance issue is caused by incorrectly using the write-combine flag.
The use case of BO_USE_SW_READ_OFTEN should not use WC, due to frequent CPU data reads.

Fixed a performance issue

---

cros_gralloc/cros_gralloc_driver.cc
cros_gralloc/gralloc1/cros_gralloc1_module.cc
i915.c

This is to help fix Coverity issues in minigbm project.
CIDs:222122 188451 203271 255440
Tracked-On: OAM-115814

INTERNAL:Fix Coverity issues

---

i915.c

The MTL doesn't support fence register and
DRM_IOCTL_I915_GEM_SET_TILING ioctl.
Tracked-On: OAM-117414

Fix the MTL-P boot issue

---

cros_gralloc/cros_gralloc_driver.cc
cros_gralloc/cros_gralloc_helpers.cc
cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Utils.cc
cros_gralloc/mapper_stablec/Mapper.cpp
drv.h
drv_helpers.c
i915.c

Refer to NV12 format, for P010,
sw render use:
HAL_PIXEL_FORMAT_YCBCR_P010 => DRM_FORMAT_P010
hw render use:
HAL_PIXEL_FORMAT_P010_INTEL => DRM_FORMAT_P010_INTEL
The HAL_PIXEL_FORMAT_YCBCR_420_888 convert to NV12 format to create bo. Add special check for it.
Tracked-On: OAM-118214

Fixed codec format mismatch issue

---

cros_gralloc/cros_gralloc_driver.cc
cros_gralloc/cros_gralloc_helpers.cc
cros_gralloc/cros_gralloc_helpers.h
cros_gralloc/gralloc1/cros_gralloc1_module.cc
cros_gralloc/gralloc4/CrosGralloc4Mapper.cc

In minigbm, we convert the drm_format in function
drv_resolve_format_and_use_flags_helper to create bo. 
Do not invert bo.format as droid_format value.
This patch revert the comimit: https://github.com/projectceladon/minigbm/commit/0eeee785f7f59233db647e6dc408a859801a8f8e of Android Q.
With this patch, do not need this hardcode: https://github.com/projectceladon/minigbm/commit/a5ca9e4b8aabd0ab391be3d15f41a1cbef75ab31.
Tracked-On: OAM-118207

Fix the format mismatch issue.

---

i915.c

Check for tile 4 was causing bo_map to fail for avif format. Removing this check was previously causing failure for DRM_IOCTL_I915_GEM_MMAP_GTT.
As part of the dGPU support enablement patch 30ec0522, support for tile 4 has been added. Hence removing te check for tile 4 doesn't cause any failure.
Tracked-On: OAM-118420

Remove check that fails mapping for tile 4

---

cros_gralloc/cros_gralloc_driver.cc
i915.c

* Dereference after null check
* Unused value
Tracked-On: OAM-121343

Fixed some coverity issues

---

cros_gralloc/cros_gralloc_driver.cc
drv.c
drv.h
gbm.c

This PR rever the commit b5053aa29930 as it casues the graphic type set fail.
Android VM boot fail if seperate the drv array init and drv init before. Now this issue not reproduced. So change it back.
Tracked-On: OAM-122333

The graphic type should be set before driver init
